-- local module = require(GetScriptDirectory().."/helpers")
-- local behavior = require(GetScriptDirectory().."/behavior")
-- local stateMachine = require(GetScriptDirectory().."/state_machine")
-- local minionBehavior = require(GetScriptDirectory().."/minion_behavior")
-- local minionStateMachine = require(GetScriptDirectory().."/minion_state_machine")
-- function Think()
-- 	local npcBot = GetBot()
-- 	local state = stateMachine.calculateState(npcBot)
-- 	behavior.generic(npcBot, state)
-- end
-- function MinionThink(hMinionUnit)
-- 	local state = minionStateMachine.calculateState(hMinionUnit)
-- 	local master = GetBot()
-- 	if (hMinionUnit == nil) then
-- 		return
-- 	end
-- 	if hMinionUnit:IsIllusion() then
-- 		minionBehavior.generic(hMinionUnit, master, state)
-- 	else
-- 		return
-- 	end
-- end